### ISSUE TITLE
有人是黑色，没人是白色

### ISSUE THREAD

**Issue by Keneyr** [otnt/kinect2.0-opencv#2]
是否颠倒了。应该是有人是白色，没人是黑色

**Comment by otnt** [comment]
你好，谢谢你的关注。遗憾的是这个项目很久了，而我已经很久没有开发kinect相关内容，所以无法给你答复，抱歉。

**Comment by Keneyr** [comment]
谢谢。有人的区域是黑色，没人的区域是白色。作者的注释是对的。
